name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- python=3.6
- pip
- numpy
- matplotlib
- astropy
- scipy
- jupyter

- pip:
  - git+https://github.com/mfixstsci/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git
  - ci-watson
